version: '3.7'
  services:
    postgres:
      image: postgres:latest
      ports:
        - '5432:5432'
  restart: always
  environment:
    - POSTGRES_RANDOM_ROOT_PASSWORD=yes
    - POSTGRES_DB=app
    - POSTGRES_USER=app
    - POSTGRES_PASSWORD=pass
nodejs:
  build: ./gate-simulator
  ports:
    - '9999:9999'
    -
