version: '3.7'
  services:
    node:
      build: artifacts/gate-simulator
      image: node-app:1.0
      container_name: node
      ports:
        - '9999:9999'
      command: npm start

    postgres:
      image: postgres:12.0-alpine
      container_name: pstg-container1
      ports:
        - '5432:5432'
      volumes:
        - ./data_postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=app
        - POSTGRES_USER=app
        - POSTGRES_PASSWORD=pass
